# -*- coding: utf-8 -*-
"""FFNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RjXAZldBSgy-ZgQgu1zH5J8bvwffqkwm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy
import sys
import os
import pickle
import librosa
import librosa.display
from IPython.display import Audio
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow import keras

from keras import layers
import keras

df1 = pd.read_csv('/content/features_3_sec.csv')
df1.head()

df1.shape

df1.dtypes

df1 = df1.drop(labels='filename',axis=1)

genre_list = df1.iloc[:, -1]
encoder = LabelEncoder()

y = encoder.fit_transform(genre_list)

print(df1.iloc[:, :-1])

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(np.array(df1.iloc[:, :-1], dtype = float))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

from keras.models import Sequential

# Neural network
model = Sequential()
model.add(layers.Dense(256, activation='relu', input_shape=(X_train.shape[1],)))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

classifier = model.fit(X_train,
                    y_train,
                    epochs=100,
                    batch_size=128)

test_loss, test_acc  = model.evaluate(X_test, y_test, batch_size=128)

print("The test loss is :",test_loss, "\nThe test accuracy is :",test_acc)

model.summary()

hist

plt.plot(hist['loss'])

